export const questions = [
  {
    id: 'gender',
    question: 'What is your gender?',
    type: 'single',
    dataOnly: true,
    options: ['Male', 'Female', 'Non-Binary', 'Prefer not to say'],
  },
  {
    id: 'age',
    question: 'What is your age?',
    type: 'single',
    dataOnly: true,
    options: ['17-24', '25-34', '35-44', '45-54', '55-64', '64+'],
  },
  {
    id: 'postcode',
    question: 'What is your postcode?',
    type: 'text',
    dataOnly: true,
    placeholder: 'e.g. SW1A 1AA',
  },
  {
    id: 'radius',
    question: 'What is your preferred search radius?',
    type: 'single',
    dataOnly: true,
    options: ['Up to 10 miles', 'Up to 25 miles', 'Up to 50 miles', 'Up to 100 miles', 'Nationwide'],
  },
  {
    id: 'budget',
    question: 'What is your budget?',
    type: 'budget',
    hint: 'Enter your minimum and maximum budget for a used car.',
  },
  {
    id: 'purchaseMethod',
    question: 'How are you planning to pay?',
    type: 'single',
    hint: 'This helps us show you the true cost of ownership.',
    options: ['Cash', 'Part exchange', 'Hire Purchase (HP)', 'Personal Contract Purchase (PCP)'],
  },
  {
    id: 'deposit',
    question: 'How much deposit can you put down?',
    type: 'deposit',
    hint: 'Enter the amount you can put down upfront.',
    showIf: (answers) => ['Hire Purchase (HP)', 'Personal Contract Purchase (PCP)'].includes(answers.purchaseMethod),
  },
  {
    id: 'transmission',
    question: 'Do you have a preferred transmission?',
    type: 'single',
    options: ['Automatic', 'Manual', 'No preference'],
  },
  {
    id: 'fuel',
    question: 'Do you have a preferred fuel type?',
    type: 'single',
    options: ['Petrol', 'Diesel', 'Hybrid', 'Electric', 'No preference'],
  },
  {
    id: 'bodyType',
    question: 'Do you have a preferred body type?',
    type: 'single',
    options: ['Hatchback', 'Saloon', 'Estate', 'SUV', 'Crossover', 'MPV', 'Coupe', 'Van', 'No preference'],
  },
  {
    id: 'driving',
    question: 'Where do you mostly drive?',
    type: 'single',
    options: ['Mostly city', 'Mostly motorway', 'Mostly rural', 'Mixed driving'],
  },
  {
    id: 'mileage',
    question: 'Roughly how many miles do you drive per year?',
    type: 'single',
    options: ['Under 3,000', '3,000-5,000', '5,000-8,000', '8,000-15,000', '15,000+'],
  },
  {
    id: 'runningCosts',
    question: 'How important are low running costs?',
    type: 'single',
    options: ['Not a concern', 'Something I would consider', 'Somewhat important', 'Extremely important'],
  },
  {
    id: 'space',
    question: 'How much space do you need?',
    type: 'single',
    options: ['Just me / couple', 'Small family', 'Family + luggage', 'As much as possible'],
  },
  {
    id: 'reliability',
    question: 'Do you want something very reliable, or are you happy with a bit of risk?',
    type: 'single',
    options: ['Maximum reliability', 'Balanced', 'Happy with some risk'],
  },
  {
    id: 'ulez',
    question: 'Do you need the car to be ULEZ compliant?',
    type: 'single',
    options: ['Yes', 'No', 'Indifferent'],
  },
  {
    id: 'email',
    question: 'Want us to send you your results?',
    type: 'e
